language: python

python:
  - 3.4
  - 3.5
  - 3.6

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database playlists;' -U postgres

script:
  - python manage.py test
