# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists_api', '0002_auto_20171028_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
